version: "3"

services:
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_DB: test_k8s
      POSTGRES_USER: test_k8s
      POSTGRES_PASSWORD: OwOtBep9Frut
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
