apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: edu-yelena-malceva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: yelena0000/django-site:90e13cf
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: postgres-ssl
        - secretRef:
            name: bucket
        - secretRef:
            name: django-secret
        - configMapRef:
            name: django-config
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/ssl/certs
          readOnly: true
      volumes:
      - name: ssl-certs
        secret:
          secretName: postgres-ssl
          items:
          - key: root.crt
            path: root.crt
          defaultMode: 384