apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: edu-yelena-malceva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: yelena0000/django-site:5297f42
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: postgres-ssl
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "webapp.settings"
        - name: SECRET_KEY
          value: "temp-key-for-dev"
        - name: DATABASE_URL
          value: "postgres://edu-yelena-malceva:DlQ%k629CG_fAWnW@c-c9qqnvghed3mn4a48p39.rw.mdb.yandexcloud.net:6432/edu-yelena-malceva?sslmode=verify-full&sslrootcert=/etc/ssl/certs/root.crt"
        volumeMounts:
        - name: media
          mountPath: /webapp/src/media
        - name: ssl-certs
          mountPath: /etc/ssl/certs
          readOnly: true
      volumes:
      - name: media
        emptyDir: {}
      - name: ssl-certs
        secret:
          secretName: postgres-ssl
          items:
          - key: root.crt
            path: root.crt
          defaultMode: 384