apiVersion: v1
kind: ConfigMap
metadata:
  name: main-nginx-config
  namespace: edu-yelena-malceva
data:
  nginx.conf: |
    user nginx;
    worker_processes  2;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen 80;
        server_name edu-yelena-malceva.yc-sirius-dev.pelid.team;

        location / {
          proxy_pass http://django-service:8000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
          return 301 https://storage.yandexcloud.net/edu-yelena-malceva/static$request_uri;
        }
    
        location /media/ {
          return 301 https://storage.yandexcloud.net/edu-yelena-malceva/media$request_uri;
        }
      }
    }