apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-nginx
  namespace: edu-yelena-malceva
  uid: 1e762430-2c64-4fdf-9042-624d5497ea9e
  resourceVersion: '123161191'
  generation: 2
  creationTimestamp: '2025-08-18T09:25:39Z'
  annotations:
    deployment.kubernetes.io/revision: '2'
  selfLink: /apis/apps/v1/namespaces/edu-yelena-malceva/deployments/main-nginx
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-08-18T09:25:40Z'
      lastTransitionTime: '2025-08-18T09:25:40Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-08-24T11:02:37Z'
      lastTransitionTime: '2025-08-18T09:25:39Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "main-nginx-6b859dd4f7" has successfully progressed.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: main-nginx
      annotations:
        kubectl.kubernetes.io/restartedAt: '2025-08-24T14:02:38+03:00'
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: main-nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
            defaultMode: 420
            optional: false
      containers:
        - name: nginx
          image: nginx:1.16.1
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: nginx-config
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              mountPropagation: None
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: true
      shareProcessNamespace: false
      securityContext: {}
      schedulerName: default-scheduler
      enableServiceLinks: true
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
