apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2025-08-18T09:25:39Z"
  generation: 2
  name: main-nginx
  namespace: edu-yelena-malceva
  resourceVersion: "123161191"
  uid: 1e762430-2c64-4fdf-9042-624d5497ea9e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: main-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-08-24T14:02:38+03:00"
      creationTimestamp: null
      labels:
        app: main-nginx
    spec:
      automountServiceAccountToken: true
      containers:
      - image: nginx:1.16.1
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          mountPropagation: None
          name: nginx-config
          readOnly: true
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: nginx.conf
            path: nginx.conf
          name: main-nginx-config
          optional: false
        name: nginx-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-08-18T09:25:40Z"
    lastUpdateTime: "2025-08-18T09:25:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-08-18T09:25:39Z"
    lastUpdateTime: "2025-08-24T11:02:37Z"
    message: ReplicaSet "main-nginx-6b859dd4f7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
