apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  SECRET_KEY: c29tZS1zZWNyZXQta2V5LWZvci10ZXN0
  DATABASE_URL: cG9zdGdyZXM6Ly90ZXN0X2s4czpPd090QmVwOUZydXRAMTcyLjI5LjI0OC43MTo1NDMyL3Rlc3Rfazhz